name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Check Node and npm versions for debugging
      - name: Check Node.js and npm version
        run: |
          node -v
          npm -v

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Run tests (if any)
      - name: Run tests
        run: npm test
        continue-on-error: true  # Ensure tests do not halt the workflow

      # Step 7: Debugging before deployment
      - name: Debug Step
        run: |
          echo "Current Directory:"
          pwd
          echo "Files in the directory:"
          ls -al

      # Step 8: Simulate Deployment
      - name: Simulate Deployment
        run: |
          echo "Deploying to test environment..."
          echo "Deployment successful!"

