name: CI/CD Pipeline for Shell Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck

    - name: Lint Shell Scripts
      run: |
        shellcheck *.sh

    - name: Run Unit Tests
      run: |
        # Example: Test if scripts execute without syntax errors
        for script in *.sh; do
          bash -n "$script" || exit 1
        done
      shell: bash

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H <your-server-ip-or-hostname> >> ~/.ssh/known_hosts

    - name: Deploy Shell Scripts
      run: |
        scp *.sh user@<your-server-ip-or-hostname>:/path/to/deployment/
        ssh user@<your-server-ip-or-hostname> "chmod +x /path/to/deployment/*.sh && /path/to/deployment/deploy.sh"

