name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensures deploy job runs after build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Node.js (if using a static site generator or bundler)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build # Customize based on your build script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Replace with the directory containing the built files

